version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
    env_file:
      - .env

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    restart: always
    env_file:
      - .env

volumes:
  db_data:
  wp_data:

networks:
  inception:
    driver: bridge
